#!/bin/bash

function dom0_plugin_location {
    for PLUGIN_DIR in "/etc/xapi.d/plugins" "/usr/lib/xcp/plugins" "/usr/lib/xapi/plugins" "/usr/lib64/xapi/plugins"; do
        if [ -d $PLUGIN_DIR ]; then
            echo $PLUGIN_DIR
            return 0
        fi
    done
    return 1
}
